cache:
  paths:
    - .pip
    - .tox

before_script:
  - pip --cache-dir=.pip install tox

py27:
  image: python:2.7
  script:
    - tox -e py27
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'

py36:
  image: python:3.6
  script:
    - tox -e py36
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'

py37:
  image: python:3.7
  script:
    - tox -e py37
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'

docker:
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f docker/docker-compose.yml build
  tags:
    - docker-in-docker
